MERGE 
	[DESTINATION_SERVER].[DESTINATION_DATABASE].dbo.[DESTINATION_TABLE] trgt
USING
	[SOURCE_SERVER].[SOURCE_DATABASE].dbo.[SOURCE_TABLE] src
ON SEARCH_CONDITIONS
	WHEN MATCHED 
THEN 
	UPDATE  SET
	TABLE_UPDATE_LIST 
	WHEN NOT MATCHED 
THEN
	INSERT
	 (TABLE_COLUMN_LIST) 
  VALUES
  (TABLE_INSERT_LIST);