SELECT * into #TEMP_TABLE FROM OPENQUERY( [SOURCE_SERVER],  'SELECT * FROM  [SOURCE_DATABASE].dbo.[SOURCE_TABLE]');

MERGE 
	[DESTINATION_DATABASE].dbo.[DESTINATION_TABLE] as TARGET
USING
	 #TEMP_TABLE   as SOURCE
ON SEARCH_CONDITIONS
	WHEN MATCHED 
THEN 
	UPDATE  SET TABLE_UPDATE_LIST
--WHEN NOT MATCHED BY SOURCE 
--	THEN DELETE	
WHEN NOT MATCHED 
	THEN 
INSERT 
  (TABLE_COLUMN_LIST) 
 VALUES
 (TABLE_INSERT_LIST);